package com.github.coutinhonobre.domain.feature.signup.exception

class SignUpAuthUserCollisionException: Exception("User already exists")